import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — Sponsio",
  description:
    "Terms of Use for Sponsio: team tokens are meme coins, the Reward Pool is a discretionary promotional program, no rewards are guaranteed.",
};

const SECTIONS: { h: string; p: string[] }[] = [
  {
    h: "1. Acceptance & eligibility",
    p: [
      "These Terms of Use govern your access to and use of sponsio.world and related interfaces (the \"Service\"), operated by the Sponsio team (\"we\", \"us\"). By using the Service you agree to these Terms and our Privacy Policy. If you do not agree, do not use the Service.",
      "You must be at least 18 years old and legally able to enter into a binding contract. The Service is not offered to persons or entities residing in, located in, or organized under the laws of any jurisdiction where use of the Service, digital assets, or promotional reward programs is prohibited or restricted, nor to persons on any applicable sanctions list (\"Restricted Persons\"). You are solely responsible for ensuring that your use of the Service, and any trading of digital assets, is lawful where you live and where you access the Service. Circumventing geographic restrictions, including via VPN, is prohibited.",
    ],
  },
  {
    h: "2. The Service",
    p: [
      "Sponsio is an informational interface for a tournament-themed token market built around the 2026 World Cup. The Service displays match schedules, token information, and market data, and links to third-party platforms where tokens are launched and traded (including BasedBid and Uniswap on the Base network).",
      "The Service is strictly non-custodial. We never hold your funds, private keys, or digital assets, we operate no user accounts, and we cannot execute, reverse, or modify any transaction. All trading occurs through autonomous third-party smart contracts and platforms that we do not control, via wallets that only you control.",
    ],
  },
  {
    h: "3. Team tokens are meme coins",
    p: [
      "All team tokens referenced on the Service (the 48 World Cup team tokens and any related tokens, collectively \"Team Tokens\") are meme coins: digital collectibles inspired by sporting culture and fan enthusiasm, purchased for entertainment, cultural participation, and the expression of support for a team.",
      "Team Tokens convey no rights of any kind. They are not shares, equity, debt, or any other security or financial instrument. They carry no ownership interest, no dividend, no interest, no revenue share, no governance rights, and no claim against us, any team, any federation, or any other person or entity. They generate no yield and entitle the holder to nothing beyond the token itself.",
      "The price of a Team Token is driven entirely by market sentiment and speculative trading. It has no intrinsic value, its value may be extremely volatile, and it may fall to zero. You should be prepared to lose the entire amount you spend on Team Tokens.",
      "This characterization is consistent with published regulatory staff guidance on meme coins (including the U.S. SEC Division of Corporation Finance staff statement on meme coins, February 2025), under which meme coins of this nature are generally not offers or sales of securities, because purchasers do not acquire a right to profits derived from the managerial efforts of others. Nothing on the Service is, or should be read as, an offer of securities, investment advice, or a promise of profit.",
      "TEAM TOKENS DO NOT GUARANTEE ANY REWARD, RETURN, PAYOUT, OR PROFIT OF ANY KIND. Buying, holding, or trading Team Tokens — including holding the token of the eventual champion — creates no entitlement to compensation from us beyond participation, on these Terms, in the discretionary Reward Pool described below, if and to the extent it is funded and distributed.",
    ],
  },
  {
    h: "4. The Reward Pool — a discretionary promotional program",
    p: [
      "During the tournament we may operate a single promotional reward pool (the \"Reward Pool\") funded from fees generated by Team Token launch and trading activity. The Reward Pool is not funded by user deposits, is not a bet or wager, is not interest or yield, and is not an investment return. It is a discretionary promotional program.",
      "Intended mechanics, described in detail on the Service: random balance snapshots are taken in each 24-hour window of the tournament; after the final, the champion team determines the champion token; each eligible wallet's share equals its average champion-token balance across all tournament snapshots divided by the sum of all such averages. Methodology, snapshot data, and claim instructions will be published.",
      "The size of the Reward Pool is unknown in advance, depends entirely on actual fee generation, and may be small or zero. We reserve the right to modify the methodology for accuracy or security reasons, to exclude addresses engaged in manipulation, wash trading, or exploits, to exclude contract-held balances (including liquidity pools and platform contracts) per the published methodology, to impose claim eligibility requirements including geographic restrictions and compliance checks, and to set a reasonable claim deadline after which unclaimed amounts may be redirected. If the tournament is cancelled, abandoned, or materially altered, we may adjust, postpone, or cancel the distribution. No payout is owed to any person until it is published as claimable and validly claimed.",
    ],
  },
  {
    h: "5. Fees",
    p: [
      "Token launches and trading are subject to fees set by the third-party platforms involved (launch fees, trading fees, liquidity fees) and to blockchain network gas fees. A portion of such fees may accrue to us and may, at our discretion, fund the Reward Pool. All fees are final and non-refundable once a transaction is confirmed on-chain, regardless of outcome.",
    ],
  },
  {
    h: "6. Risks",
    p: [
      "Trading meme coins involves a high risk of total loss. Prices are extremely volatile and sentiment-driven. Smart contracts may contain bugs or be exploited. Blockchain transactions are irreversible. Third-party platforms may fail, pause, or change terms. Liquidity may be thin or disappear, especially for teams eliminated from the tournament. Regulatory treatment of digital assets varies and may change. Nothing on the Service is financial, investment, legal, or tax advice — do your own research and never spend more than you can afford to lose.",
    ],
  },
  {
    h: "7. Third-party services",
    p: [
      "The Service links to and depends on third parties — including BasedBid, Uniswap, the Base network, block explorers, and wallet providers — each governed by its own terms and policies. We do not control them, make no warranties about them, and accept no liability for losses arising from their use. Interacting with them is your decision and your risk.",
    ],
  },
  {
    h: "8. Prohibited uses",
    p: [
      "You agree not to: use the Service in violation of any law; use it from a restricted jurisdiction or as a Restricted Person; engage in market manipulation, wash trading, spoofing, or fraud; attack, probe, overload, or interfere with the Service or related infrastructure; use bots or automated tools to abuse the Service or any reward mechanism; impersonate any person; or attempt to game reward snapshots through deceptive on-chain activity. We may restrict access and exclude addresses from any promotional program for violations.",
    ],
  },
  {
    h: "9. Intellectual property & no affiliation",
    p: [
      "The Service's original content, design, and branding belong to us. Team names, country names, and flags are used solely as nominative identifiers of national football teams competing in a public sporting event.",
      "Sponsio is not affiliated with, endorsed by, or sponsored by FIFA, any national football federation, any team, or any player. All trademarks belong to their respective owners. Team Tokens are independent meme coins and are not official products of any sporting organization.",
    ],
  },
  {
    h: "10. Disclaimers & limitation of liability",
    p: [
      "THE SERVICE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\", WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ACCURACY OF MARKET DATA, UPTIME, OR FITNESS FOR A PARTICULAR PURPOSE. DISPLAYED PRICES AND ODDS ARE INFORMATIONAL AND MAY BE DELAYED OR WRONG.",
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, TOKENS, OR DATA, ARISING FROM YOUR USE OF THE SERVICE OR ANY THIRD-PARTY PLATFORM, EVEN IF ADVISED OF THE POSSIBILITY. OUR AGGREGATE LIABILITY FOR ALL CLAIMS SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS (USD 100).",
    ],
  },
  {
    h: "11. Indemnification",
    p: [
      "You agree to indemnify and hold us harmless from any claims, damages, and expenses (including reasonable legal fees) arising from your use of the Service, your trading activity, your violation of these Terms, or your violation of any law or third-party right.",
    ],
  },
  {
    h: "12. Changes; governing law; contact",
    p: [
      "We may revise these Terms at any time by posting the updated version at this address; continued use constitutes acceptance. These Terms are governed by the laws of the operator's jurisdiction of organization, to be specified on this page upon entity formation; disputes shall be resolved in the courts of that jurisdiction. Questions about these Terms can be raised through our official channels linked in the site footer.",
    ],
  },
];

export default function Terms() {
  return (
    <>
      <section className="shrink-0 px-6 pt-28 pb-5 text-center lg:pt-24">
        <h1 className="font-serif text-3xl font-normal uppercase tracking-tight drop-shadow-[0_1px_3px_rgba(0,0,0,0.5)] md:text-4xl [-webkit-text-stroke:0.35px_rgba(0,0,0,0.85)]">
          Terms of Use
        </h1>
        <p className="mx-auto mt-2 max-w-xl text-sm font-medium text-white drop-shadow-[0_2px_10px_rgba(0,0,0,0.9)]">
          Effective date: June 6, 2026
        </p>
      </section>

      <main className="min-h-0 flex-1 overflow-y-auto px-6 pb-6 md:px-10">
        <div className="mx-auto max-w-2xl rounded-xl bg-white/85 px-6 py-5 text-zinc-900 shadow-lg shadow-black/25 ring-1 ring-black/5 backdrop-blur-md">
          {SECTIONS.map((s) => (
            <section key={s.h} className="border-b border-zinc-100 py-3 last:border-0">
              <h2 className="font-cond text-base font-semibold uppercase">{s.h}</h2>
              {s.p.map((para, i) => (
                <p key={i} className="mt-1.5 text-sm leading-relaxed text-zinc-600">
                  {para}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>
    </>
  );
}
